# Generated by Django 5.1.1 on 2024-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Создана"),
                    ("active", "complete"),
                    ("F", "Завершена"),
                ],
                max_length=20,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
