# Generated by Django 5.1.2 on 2024-10-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='date_of_first_mail',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
    ]
