# Generated by Django 5.1.1 on 2024-10-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("day", "Раз в день"),
                    ("week", "Раз в неделю"),
                    ("month", "Раз в месяц"),
                ],
                max_length=5,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Создана"),
                    ("active", "Запущена"),
                    ("complete", "Завершена"),
                ],
                max_length=8,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
